## ERT Leader

- type: entity
  id: RandomHumanoidSpawnerERTLeaderAmber
  name: ERT leader
  suffix: ERTRole, Amber, Uplink
  components:
    - type: Sprite
      sprite: Markers/jobs.rsi
      state: ertleader
    - type: RandomMetadata
      nameSegments:
      - NamesMilitaryFirstLeader
      - NamesMilitaryLast
    - type: RandomHumanoidSpawner
      settings: ERTLeaderAmber

- type: entity
  id: RandomHumanoidSpawnerERTLeaderAmberLock
  name: ERT leader
  suffix: ERTRole, Amber, Uplink, Lock
  components:
    - type: Sprite
      sprite: Markers/jobs.rsi
      state: ertleader
    - type: RandomMetadata
      nameSegments:
      - NamesMilitaryFirstLeader
      - NamesMilitaryLast
    - type: RandomHumanoidSpawner
      settings: ERTLeaderAmberLock

- type: randomHumanoidSettings
  id: ERTLeaderAmber
  speciesBlacklist:
  - Diona
  - Vox
  - Felinid
  - Moth
  - Arachnid
  - Reptilian
  - Vulpkanin
  - Swine
  - Tajaran
  - Demon
  - SlimePerson
  - Dwarf
  parent: EventHumanoidMindShielded
  randomizeName: false
  components:
    - type: GhostRole
      name: ghost-role-information-ert-leader-name
      description: ghost-role-information-ert-leader-description
      rules: ghost-role-information-nonantagonist-rules
      raffle:
        settings: short
      job: ERTLeader
    - type: Loadout
      prototypes: [ ERTLeaderGearAmber ]
    - type: RandomMetadata
      nameSegments:
      - NamesMilitaryFirstLeader
      - NamesMilitaryLast

- type: randomHumanoidSettings
  id: ERTLeaderAmberLock
  parent: ERTLeaderAmber
  randomizeName: false
  components:
    - type: GhostRole
      requirements:
      - !type:OverallPlaytimeRequirement
        time: 43200 # 12h
      - !type:DepartmentTimeRequirement
        department: Security
        time: 18000 # 5h
      - !type:DepartmentTimeRequirement
        department: Command
        time: 18000 # 5h
      name: ghost-role-information-ert-leader-name
      description: ghost-role-information-ert-leader-description
      rules: ghost-role-information-nonantagonist-rules
      raffle:
        settings: short
      job: ERTLeader
    - type: Loadout
      prototypes: [ ERTLeaderGearAmber ]
    - type: RandomMetadata
      nameSegments:
      - NamesMilitaryFirstLeader
      - NamesMilitaryLast

- type: entity
  id: RandomHumanoidSpawnerERTLeaderRed
  parent: RandomHumanoidSpawnerERTLeaderAmber
  name: ERT leader
  suffix: ERTRole, Red, Uplink
  components:
    - type: Sprite
      sprite: Markers/jobs.rsi
      state: ertleadereva
    - type: RandomHumanoidSpawner
      settings: ERTLeaderRed

- type: entity
  id: RandomHumanoidSpawnerERTLeaderRedLock
  parent: RandomHumanoidSpawnerERTLeaderRed
  suffix: ERTRole, Amber, Uplink, Lock
  components:
    - type: RandomHumanoidSpawner
      settings: ERTLeaderRedLock

- type: randomHumanoidSettings
  id: ERTLeaderRed
  parent: ERTLeaderAmber
  components:
    - type: GhostRole
      name: ghost-role-information-ert-leader-name
      description: ghost-role-information-ert-leader-description
      rules: ghost-role-information-nonantagonist-rules
      raffle:
        settings: short
      job: ERTLeader
    - type: Loadout
      prototypes: [ ERTLeaderGearRed ]

- type: randomHumanoidSettings
  id: ERTLeaderRedLock
  parent: ERTLeaderRed
  components:
    - type: GhostRole
      requirements:
      - !type:OverallPlaytimeRequirement
        time: 43200 # 12h
      - !type:DepartmentTimeRequirement
        department: Security
        time: 18000 # 5h
      - !type:DepartmentTimeRequirement
        department: Command
        time: 18000 # 5h
      name: ghost-role-information-ert-leader-name
      description: ghost-role-information-ert-leader-description
      rules: ghost-role-information-nonantagonist-rules
      raffle:
        settings: short
      job: ERTLeader
    - type: Loadout
      prototypes: [ ERTLeaderGearRed ]

- type: entity
  id: RandomHumanoidSpawnerERTLeaderGamma
  parent: RandomHumanoidSpawnerERTLeaderRed
  suffix: ERTRole, Gamma, Uplink
  components:
    - type: RandomHumanoidSpawner
      settings: ERTLeaderGamma

- type: entity
  id: RandomHumanoidSpawnerERTLeaderGammaLock
  parent: RandomHumanoidSpawnerERTLeaderRed
  suffix: ERTRole, Gamma, Uplink, Lock
  components:
    - type: RandomHumanoidSpawner
      settings: ERTLeaderGammaLock

- type: randomHumanoidSettings
  id: ERTLeaderGamma
  parent: ERTLeaderAmber
  components:
    - type: GhostRole
      name: ghost-role-information-ert-leader-name
      description: ghost-role-information-ert-leader-description
      rules: ghost-role-information-nonantagonist-rules
      raffle:
        settings: short
      job: ERTLeader
    - type: Loadout
      prototypes: [ ERTLeaderGearGamma ]

- type: randomHumanoidSettings
  id: ERTLeaderGammaLock
  parent: ERTLeaderGamma
  components:
    - type: GhostRole
      requirements:
      - !type:OverallPlaytimeRequirement
        time: 43200 # 12h
      - !type:DepartmentTimeRequirement
        department: Security
        time: 18000 # 5h
      - !type:DepartmentTimeRequirement
        department: Command
        time: 18000 # 5h
      name: ghost-role-information-ert-leader-name
      description: ghost-role-information-ert-leader-description
      rules: ghost-role-information-nonantagonist-rules
      raffle:
        settings: short
      job: ERTLeader
    - type: Loadout
      prototypes: [ ERTLeaderGearGamma ]
## ERT Security

- type: entity
  id: RandomHumanoidSpawnerERTSecurityAmber
  parent: RandomHumanoidSpawnerERTLeaderAmber
  name: ERT security
  suffix: ERTRole, Amber
  components:
    - type: Sprite
      sprite: Markers/jobs.rsi
      state: ertsecurity
    - type: RandomMetadata
      nameSegments:
      - NamesMilitaryFirst
      - NamesMilitaryLast
    - type: RandomHumanoidSpawner
      settings: ERTSecurityAmber

- type: entity
  id: RandomHumanoidSpawnerERTSecurityAmberLock
  parent: RandomHumanoidSpawnerERTSecurityAmber
  suffix: ERTRole, Amber, Uplink, Lock
  components:
    - type: RandomHumanoidSpawner
      settings: ERTSecurityAmberLock

- type: randomHumanoidSettings
  id: ERTSecurityAmber
  parent: ERTLeaderAmber
  components:
    - type: GhostRole
      name: ghost-role-information-ert-security-name
      description: ghost-role-information-ert-security-description
      rules: ghost-role-information-nonantagonist-rules
      raffle:
        settings: short
      job: ERTSecurity
    - type: RandomMetadata
      nameSegments:
      - NamesMilitaryFirst
      - NamesMilitaryLast
    - type: Loadout
      prototypes: [ ERTSecurityGearAmber ]

- type: randomHumanoidSettings
  id: ERTSecurityAmberLock
  parent: ERTSecurityAmber
  components:
    - type: GhostRole
      requirements:
      - !type:OverallPlaytimeRequirement
        time: 43200 # 12h
      - !type:DepartmentTimeRequirement
        department: Security
        time: 18000 # 5h
      name: ghost-role-information-ert-security-name
      description: ghost-role-information-ert-security-description
      rules: ghost-role-information-nonantagonist-rules
      raffle:
        settings: short
      job: ERTSecurity
    - type: RandomMetadata
      nameSegments:
      - NamesMilitaryFirst
      - NamesMilitaryLast
    - type: Loadout
      prototypes: [ ERTSecurityGearAmber ]

- type: entity
  id: RandomHumanoidSpawnerERTSecurityGamma
  parent: RandomHumanoidSpawnerERTSecurityAmber
  suffix: ERTRole, Gamma
  components:
    - type: RandomHumanoidSpawner
      settings: ERTSecurityGamma

- type: entity
  id: RandomHumanoidSpawnerERTSecurityGammaLock
  parent: RandomHumanoidSpawnerERTSecurityAmber
  suffix: ERTRole, Gamma, Lock
  components:
    - type: RandomHumanoidSpawner
      settings: ERTSecurityGammaLock

- type: randomHumanoidSettings
  id: ERTSecurityGamma
  parent: ERTSecurityAmber
  components:
    - type: GhostRole
      name: ghost-role-information-ert-security-name
      description: ghost-role-information-ert-security-description
      rules: ghost-role-information-nonantagonist-rules
      raffle:
        settings: short
      job: ERTSecurity
    - type: Loadout
      prototypes: [ ERTSecurityGearGamma ]

- type: randomHumanoidSettings
  id: ERTSecurityGammaLock
  parent: ERTSecurityAmber
  components:
    - type: GhostRole
      requirements:
      - !type:OverallPlaytimeRequirement
        time: 43200 # 12h
      - !type:DepartmentTimeRequirement
        department: Security
        time: 18000 # 5h
      name: ghost-role-information-ert-security-name
      description: ghost-role-information-ert-security-description
      rules: ghost-role-information-nonantagonist-rules
      raffle:
        settings: short
      job: ERTSecurity
    - type: Loadout
      prototypes: [ ERTSecurityGearGamma ]

## ERT Chaplain

- type: entity
  id: RandomHumanoidSpawnerERTChaplainAmber
  parent: RandomHumanoidSpawnerERTLeaderAmber
  name: ERT chaplain
  suffix: ERTRole, Amber
  components:
    - type: Sprite
      sprite: Markers/jobs.rsi
      state: chaplain #needs an ERT variant once a good suit it made.
    - type: RandomMetadata
      nameSegments:
      - NamesMilitaryFirst
      - NamesMilitaryLast
    - type: RandomHumanoidSpawner
      settings: ERTChaplainAmber

- type: randomHumanoidSettings
  id: ERTChaplainAmber
  parent: ERTLeaderAmber
  components:
    - type: BibleUser
    - type: GhostRole
      name: ghost-role-information-ert-chaplain-name
      description: ghost-role-information-ert-chaplain-description
      rules: ghost-role-information-nonantagonist-rules
      raffle:
        settings: short
      job: ERTChaplain
    - type: RandomMetadata
      nameSegments:
      - NamesMilitaryFirst
      - NamesMilitaryLast
    - type: Loadout
      prototypes: [ ERTChaplainGearAmber ]

## ERT Janitor

- type: entity
  id: RandomHumanoidSpawnerERTJanitorAmber
  parent: RandomHumanoidSpawnerERTLeaderAmber
  name: ERT janitor
  suffix: ERTRole, Amber
  components:
    - type: Sprite
      sprite: Markers/jobs.rsi
      state: ertjanitor
    - type: RandomMetadata
      nameSegments:
      - NamesMilitaryFirst
      - NamesMilitaryLast
    - type: RandomHumanoidSpawner
      settings: ERTJanitorAmber

- type: randomHumanoidSettings
  id: ERTJanitorAmber
  parent: ERTLeaderAmber
  components:
    - type: GhostRole
      name: ghost-role-information-ert-janitor-name
      description: ghost-role-information-ert-janitor-description
      rules: ghost-role-information-nonantagonist-rules
      raffle:
        settings: short
      job: ERTJanitor
    - type: RandomMetadata
      nameSegments:
      - NamesMilitaryFirst
      - NamesMilitaryLast
    - type: Loadout
      prototypes: [ ERTJanitorGearAmber ]

- type: entity
  id: RandomHumanoidSpawnerERTJanitorGamma
  parent: RandomHumanoidSpawnerERTJanitorAmber
  name: ERT janitor
  suffix: ERTRole, Gamma
  components:
    - type: Sprite
      sprite: Markers/jobs.rsi
      state: ertjanitoreva
    - type: RandomHumanoidSpawner
      settings: ERTJanitorGamma

- type: randomHumanoidSettings
  id: ERTJanitorGamma
  parent: ERTJanitorAmber
  components:
    - type: GhostRole
      name: ghost-role-information-ert-janitor-name
      description: ghost-role-information-ert-janitor-description
      rules: ghost-role-information-nonantagonist-rules
      raffle:
        settings: short
      job: ERTJanitor
    - type: Loadout
      prototypes: [ ERTJanitorGearGamma ]

## ERT Engineer

- type: entity
  id: RandomHumanoidSpawnerERTEngineerAmber
  parent: RandomHumanoidSpawnerERTLeaderAmber
  name: ERT engineer
  suffix: ERTRole, Amber
  components:
    - type: Sprite
      sprite: Markers/jobs.rsi
      state: ertengineer
    - type: RandomMetadata
      nameSegments:
      - NamesMilitaryFirst
      - NamesMilitaryLast
    - type: RandomHumanoidSpawner
      settings: ERTEngineerAmber

- type: entity
  id: RandomHumanoidSpawnerERTEngineerAmberLock
  parent: RandomHumanoidSpawnerERTLeaderAmber
  name: ERT engineer
  suffix: ERTRole, Amber, Lock
  components:
    - type: Sprite
      sprite: Markers/jobs.rsi
      state: ertengineer
    - type: RandomMetadata
      nameSegments:
      - NamesMilitaryFirst
      - NamesMilitaryLast
    - type: RandomHumanoidSpawner
      settings: ERTEngineerAmberLock

- type: randomHumanoidSettings
  id: ERTEngineerAmber
  parent: ERTLeaderAmber
  components:
    - type: GhostRole
      name: ghost-role-information-ert-engineer-name
      description: ghost-role-information-ert-engineer-description
      rules: ghost-role-information-nonantagonist-rules
      raffle:
        settings: short
      job: ERTEngineer
    - type: RandomMetadata
      nameSegments:
      - NamesMilitaryFirst
      - NamesMilitaryLast
    - type: Loadout
      prototypes: [ ERTEngineerGearAmber ]

- type: randomHumanoidSettings
  id: ERTEngineerAmberLock
  parent: ERTLeaderAmber
  components:
    - type: GhostRole
      requirements:
      - !type:OverallPlaytimeRequirement
        time: 43200 # 12h
      - !type:DepartmentTimeRequirement
        department: Engineering
        time: 18000 # 5h
      name: ghost-role-information-ert-engineer-name
      description: ghost-role-information-ert-engineer-description
      rules: ghost-role-information-nonantagonist-rules
      raffle:
        settings: short
      job: ERTEngineer
    - type: RandomMetadata
      nameSegments:
      - NamesMilitaryFirst
      - NamesMilitaryLast
    - type: Loadout
      prototypes: [ ERTEngineerGearAmber ]

- type: entity
  id: RandomHumanoidSpawnerERTEngineerGamma
  parent: RandomHumanoidSpawnerERTEngineerAmber
  name: ERT engineer
  suffix: ERTRole, Gamma
  components:
    - type: Sprite
      sprite: Markers/jobs.rsi
      state: ertengineereva
    - type: RandomHumanoidSpawner
      settings: ERTEngineerGamma

- type: entity
  id: RandomHumanoidSpawnerERTEngineerGammaLock
  parent: RandomHumanoidSpawnerERTEngineerAmber
  name: ERT engineer
  suffix: ERTRole, Gamma, Lock
  components:
    - type: Sprite
      sprite: Markers/jobs.rsi
      state: ertengineereva
    - type: RandomHumanoidSpawner
      settings: ERTEngineerGammaLock

- type: randomHumanoidSettings
  id: ERTEngineerGamma
  parent: ERTEngineerAmber
  components:
    - type: GhostRole
      name: ghost-role-information-ert-engineer-name
      description: ghost-role-information-ert-engineer-description
      rules: ghost-role-information-nonantagonist-rules
      raffle:
        settings: short
      job: ERTEngineer
    - type: Loadout
      prototypes: [ ERTEngineerGearGamma ]

- type: randomHumanoidSettings
  id: ERTEngineerGammaLock
  parent: ERTEngineerAmber
  components:
    - type: GhostRole
      requirements:
      - !type:OverallPlaytimeRequirement
        time: 43200 # 12h
      - !type:DepartmentTimeRequirement
        department: Engineering
        time: 18000 # 5h
      name: ghost-role-information-ert-engineer-name
      description: ghost-role-information-ert-engineer-description
      rules: ghost-role-information-nonantagonist-rules
      raffle:
        settings: short
      job: ERTEngineer
    - type: Loadout
      prototypes: [ ERTEngineerGearGamma ]

## ERT Medic

- type: entity
  id: RandomHumanoidSpawnerERTMedicalAmber
  parent: RandomHumanoidSpawnerERTLeaderAmber
  name: ERT medic
  suffix: ERTRole, Amber
  components:
    - type: Sprite
      sprite: Markers/jobs.rsi
      state: ertmedical
    - type: RandomMetadata
      nameSegments:
      - NamesMilitaryFirst
      - NamesMilitaryLast
    - type: RandomHumanoidSpawner
      settings: ERTMedicalAmber

- type: entity
  id: RandomHumanoidSpawnerERTMedicalAmberLock
  parent: RandomHumanoidSpawnerERTLeaderAmber
  name: ERT medic
  suffix: ERTRole, Amber, Lock
  components:
    - type: Sprite
      sprite: Markers/jobs.rsi
      state: ertmedical
    - type: RandomMetadata
      nameSegments:
      - NamesMilitaryFirst
      - NamesMilitaryLast
    - type: RandomHumanoidSpawner
      settings: ERTMedicalAmberLock

- type: randomHumanoidSettings
  id: ERTMedicalAmber
  parent: ERTLeaderAmber
  components:
    - type: GhostRole
      name: ghost-role-information-ert-medical-name
      description: ghost-role-information-ert-medical-description
      rules: ghost-role-information-nonantagonist-rules
      raffle:
        settings: short
      job: ERTMedical
    - type: RandomMetadata
      nameSegments:
      - NamesMilitaryFirst
      - NamesMilitaryLast
    - type: Loadout
      prototypes: [ ERTMedicalGearAmber ]

- type: randomHumanoidSettings
  id: ERTMedicalAmberLock
  parent: ERTMedicalAmber
  components:
    - type: GhostRole
      requirements:
      - !type:OverallPlaytimeRequirement
        time: 43200 # 12h
      - !type:DepartmentTimeRequirement
        department: Medical
        time: 18000 # 5h
      name: ghost-role-information-ert-medical-name
      description: ghost-role-information-ert-medical-description
      rules: ghost-role-information-nonantagonist-rules
      raffle:
        settings: short
      job: ERTMedical
    - type: Loadout
      prototypes: [ ERTMedicalGearAmber ]

- type: entity
  id: RandomHumanoidSpawnerERTMedicalGamma
  parent: RandomHumanoidSpawnerERTMedicalAmber
  name: ERT medic
  suffix: ERTRole, Gamma
  components:
    - type: Sprite
      sprite: Markers/jobs.rsi
      state: ertmedicaleva
    - type: RandomHumanoidSpawner
      settings: ERTMedicalGamma

- type: entity
  id: RandomHumanoidSpawnerERTMedicalGammaLock
  parent: RandomHumanoidSpawnerERTMedicalAmber
  name: ERT medic
  suffix: ERTRole, Gamma, Lock
  components:
    - type: Sprite
      sprite: Markers/jobs.rsi
      state: ertmedicaleva
    - type: RandomHumanoidSpawner
      settings: ERTMedicalGammaLock

- type: randomHumanoidSettings
  id: ERTMedicalGamma
  parent: ERTMedicalAmber
  components:
    - type: GhostRole
      name: ghost-role-information-ert-medical-name
      description: ghost-role-information-ert-medical-description
      rules: ghost-role-information-nonantagonist-rules
      raffle:
        settings: short
      job: ERTMedical
    - type: Loadout
      prototypes: [ ERTMedicalGearGamma ]

- type: randomHumanoidSettings
  id: ERTMedicalGammaLock
  parent: ERTMedicalAmber
  components:
    - type: GhostRole
      requirements:
      - !type:OverallPlaytimeRequirement
        time: 43200 # 12h
      - !type:DepartmentTimeRequirement
        department: Medical
        time: 18000 # 5h
      name: ghost-role-information-ert-medical-name
      description: ghost-role-information-ert-medical-description
      rules: ghost-role-information-nonantagonist-rules
      raffle:
        settings: short
      job: ERTMedical
    - type: Loadout
      prototypes: [ ERTMedicalGearGamma ]
